server:
  servlet:
    context-path: /bank

spring:
  datasource:
    url: jdbc:postgresql://localhost:5436/postgresBank
    username: hiberusBank
    password: Hiberus123
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgresPlusDialect
    hibernate:
      ddl-auto: create

KEYPASS: Gandalf
LORE: Ã‰0wyn
BANNED: Antonio